export enum MESSAGE_ACTIONS {
    GET_RESPONSE = "[Message] Get Response",
    GET_RESPONSE_SUCCESS = "[Message] Get Response Success",
    GET_RESPONSE_FAILURE = "[Message] Get Response Failure",
    RELOAD_RESPONSE = "[Message] Reload Response",
    CLEAR_MESSAGES = "[Message] Clear Messages",
    FETCH_MESSAGES_FROM_THREAD = "[Message] Fetch Messages From Thread",
    FETCH_MESSAGES_FROM_THREAD_SUCCESS = "[Message] Fetch Messages From Thread Success",
    FETCH_MESSAGES_FROM_THREAD_FAILURE = "[Message] Fetch Messages From Thread Failure",
    MERGE_ACCUMULATED_STREAM_CONTENT = "[Message] Merge Accumulated Stream Content",
    ADD_USER_MESSAGE = "[Message] Add User Message",
    ADD_ASSISTANT_MESSAGE = "[Message] Add Assistant Message",
    ADD_TOOL_CALL = "[Message] Add Tool Call",
    UPDATE_TOOL_CALL_ARGS = "[Message] Update Tool Call Args",
    ADD_TOOL_RESULT = "[Message] Add Tool Result",
    ABORT_RESPONSE_GENERATION = "[Message] Abort Response Generation",
    TOGGLE_TOOL_TRACE = "[Message] Toggle Tool Trace",
    TOGGLE_TOOL_MESSAGE = "[Message] Toggle Tool Message",
}
